print("FRASES EN LENGUAJE LEET")
palabra= input("\n ingresa la frase o palabra: ").lower()

a = palabra.replace('a','4')
b = a.replace('b','8')
c = b.replace('c','(')
e = c.replace('e','3')
g = e.replace('g','&')
i = g.replace('i','1')
l = i.replace('l','|')
o = l.replace('o','0')
s = o.replace('s','5')
t = s.replace('t','7')
print("LENGUAJE LEET")
print (t)
